auth0:
  audience: ${AUTH0_AUDIENCE}
  audience_mgt: ${AUTH0_AUDIENCE_MGT}
  client_id: ${AUTH0_CLIENT_ID}
  client_secret: ${AUTH0_CLIENT_SECRET}
  management_domain: ${AUTH0_MGT_DOMAIN}
  role_id: ${AUTH0_ROLE_ID}
spring:
  security:
    oauth2:
        resourceserver:
            jwt:
                issuer-uri: ${AUTH0_ISSUER_URI}
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/saven}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
springdoc:
  pathsToMatch: /api/**