name: Build and deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  saven-build-deploy:

    runs-on: ubuntu-latest
    env:
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      AUTH0_AUDIENCE_MGT: ${{ secrets.AUTH0_AUDIENCE_MGT }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_MGT_DOMAIN: ${{ secrets.AUTH0_MGT_DOMAIN }}
      AUTH0_ROLE_ID: ${{ secrets.AUTH0_ROLE_ID }}
      AUTH0_ISSUER_URI: ${{ secrets.AUTH0_ISSUER_URI }}
      JDBC_DATABASE_URL: ${{ secrets.JDBC_DATABASE_URL }}
      JDBC_DATABASE_USERNAME: ${{ secrets.JDBC_DATABASE_USERNAME }}
      JDBC_DATABASE_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Push image to Docker hub
        run: docker build -t somethingsimple/saven:${{ github.sha }} .

      # - name: Login to Docker hub
      #   id: login-docker
      #   uses: uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push image to Docker hub
      #   run: docker push somethingsimple/saven:${{ github.sha }}

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-southeast-1

      # - name: Render ECS task definition
      #   id: task-def
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: task-definition.json
      #     container-name: saven-api-container
      #     image: docker.io/somethingsimple/saven:${{ github.sha }}

      # - name: Deploy Amazon ECS task definition
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: ${{ steps.task-def.outputs.task-definition }}
      #     service: saven-api
      #     cluster: saven-cluster
      #     wait-for-service-stability: false